In [1]:
import torch
import numpy as np

In [2]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device = 'mps' if torch.backends.mps.is_available() else device

## Tensors

In [3]:
my_tensor = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
], dtype=torch.float32, device=device)
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='mps:0')

In [4]:
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='mps:0')

In [5]:
my_tensor.dtype

torch.float32

In [6]:
my_tensor.device

device(type='mps', index=0)

In [7]:
my_tensor.shape

torch.Size([2, 3])

In [8]:
my_tensor.size()

torch.Size([2, 3])

In [9]:
my_tensor.requires_grad

False

In [10]:
x = torch.empty(3, 2) # uninitialized data, its random though it shows its all 0
x

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [11]:
torch.zeros(3, 2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [12]:
torch.ones(3, 2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [13]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [14]:
torch.eye(3, 2)

tensor([[1., 0.],
        [0., 1.],
        [0., 0.]])

In [15]:
torch.rand(3, 2) # from uniform distribution

tensor([[0.5018, 0.8162],
        [0.1560, 0.4704],
        [0.9378, 0.9110]])

In [16]:
torch.randn(3, 3) # from normal distribution

tensor([[ 1.6672, -0.6776,  0.9776],
        [-0.4192, -2.0178, -0.3492],
        [ 1.8158,  0.5066, -0.4667]])

In [17]:
torch.arange(3)

tensor([0, 1, 2])

In [18]:
torch.arange(start=1, end=4, step=1)

tensor([1, 2, 3])

In [19]:
x = torch.linspace(start=1, end=5, steps=10)
print(x)
print(x.shape)

tensor([1.0000, 1.4444, 1.8889, 2.3333, 2.7778, 3.2222, 3.6667, 4.1111, 4.5556,
        5.0000])
torch.Size([10])


In [20]:
torch.normal(mean=0, std=1, size=(3, 2))

tensor([[-0.8152, -0.3389],
        [-2.1069,  0.4954],
        [ 0.6610, -1.7125]])

In [21]:
x = torch.rand(3, 2)
print(x)
torch.diag(x, diagonal=-1), torch.diag(x, diagonal=0), torch.diag(x, diagonal=1)

tensor([[0.3859, 0.5898],
        [0.4029, 0.3985],
        [0.8085, 0.4960]])


(tensor([0.4029, 0.4960]), tensor([0.3859, 0.3985]), tensor([0.5898]))

In [22]:
x = torch.arange(4)

print(x.bool()) # boolean
print(x.short()) # int16
print(x.long()) # int64
print(x.half()) # float16
print(x.float()) #float32
print(x.double()) #float64
print(x.int()) # int32

tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)
tensor([0, 1, 2, 3], dtype=torch.int32)


In [23]:
np_array = np.zeros((5, 5))
tensor = torch.from_numpy(np_array)
np_back = tensor.numpy()

np_array, tensor, np_back

(array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 tensor([[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]], dtype=torch.float64),
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]))

## Math

In [24]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

In [25]:
x + y

tensor([5, 7, 9])

In [26]:
x - y

tensor([-3, -3, -3])

In [27]:
torch.true_divide(x, y)

tensor([0.2500, 0.4000, 0.5000])

In [28]:
torch.true_divide(x, 2)

tensor([0.5000, 1.0000, 1.5000])

In [29]:
x.pow(2)

tensor([1, 4, 9])

In [30]:
x.pow(3)

tensor([ 1,  8, 27])

In [31]:
x ** 2

tensor([1, 4, 9])

In [32]:
x = torch.rand(2, 5)

In [33]:
torch.sum(x, dim=0)

tensor([1.1656, 1.5266, 0.4362, 1.0305, 0.7996])

In [34]:
torch.max(x, dim=0)

torch.return_types.max(
values=tensor([0.9684, 0.9986, 0.2398, 0.8068, 0.6289]),
indices=tensor([1, 1, 1, 1, 0]))

In [35]:
torch.abs(x)

tensor([[0.1972, 0.5280, 0.1964, 0.2238, 0.6289],
        [0.9684, 0.9986, 0.2398, 0.8068, 0.1707]])

In [36]:
torch.argmax(x, dim=0)

tensor([1, 1, 1, 1, 0])

In [37]:
torch.mean(x, dim=1)

tensor([0.3548, 0.6369])

In [38]:
x = torch.rand(2, 5)
y = x.clone()
y[0, :] = torch.randn(1, y.shape[1])

torch.eq(x, y)

tensor([[False, False, False, False, False],
        [ True,  True,  True,  True,  True]])

In [39]:
x.sort(dim=0)

torch.return_types.sort(
values=tensor([[0.0227, 0.1665, 0.0715, 0.0173, 0.1374],
        [0.0313, 0.4681, 0.2732, 0.9088, 0.3715]]),
indices=tensor([[1, 0, 1, 0, 0],
        [0, 1, 0, 1, 1]]))

In [40]:
x = torch.rand(2, 5)
print(x)

torch.clamp(x, max=0.2)

tensor([[0.8738, 0.7116, 0.6955, 0.7841, 0.8803],
        [0.7921, 0.2547, 0.1517, 0.5442, 0.9595]])


tensor([[0.2000, 0.2000, 0.2000, 0.2000, 0.2000],
        [0.2000, 0.2000, 0.1517, 0.2000, 0.2000]])

## Comparison

In [41]:
x = torch.rand(3, 2)
x

tensor([[0.3282, 0.0819],
        [0.2920, 0.6874],
        [0.7303, 0.1495]])

In [42]:
x > 0

tensor([[True, True],
        [True, True],
        [True, True]])

In [43]:
x < 0

tensor([[False, False],
        [False, False],
        [False, False]])

In [44]:
torch.all(x > 0)

tensor(True)

In [45]:
torch.any(x < 0)

tensor(False)

## Matrix Multiplication

#### Matrix Multiplication

In [46]:
x = torch.rand((2, 5))
y = torch.rand((5, 3))

In [47]:
torch.mm(x, y), torch.mm(x, y).shape

(tensor([[2.1182, 1.2730, 2.6090],
         [2.3659, 1.2005, 2.7661]]),
 torch.Size([2, 3]))

#### Elementwise Multiplication (Hadamard Product)

In [48]:
x = torch.rand((2, 5))
y = torch.rand((2, 5))

x * y

tensor([[3.2979e-01, 6.7048e-02, 3.4775e-02, 2.3284e-01, 3.3874e-01],
        [3.6362e-04, 5.6128e-01, 3.5403e-01, 2.3577e-02, 4.7150e-02]])

#### Dot Product

In [49]:
x = torch.rand(5)
y = torch.rand(5)

In [50]:
torch.dot(x, y)

tensor(1.8219)

#### Batch Matrix Multiplication

In [51]:
batch, n, m, p = 32, 10, 20, 30

x = torch.rand(batch, n, m)
y = torch.rand(batch, m, p)

In [52]:
torch.bmm(x, y).shape

torch.Size([32, 10, 30])

#### Matrix Power (x^4 = x * x * x * x)

In [53]:
x = torch.arange(16).view(4, 4)

In [54]:
x ** 2, x.matrix_power(2)

(tensor([[  0,   1,   4,   9],
         [ 16,  25,  36,  49],
         [ 64,  81, 100, 121],
         [144, 169, 196, 225]]),
 tensor([[ 56,  62,  68,  74],
         [152, 174, 196, 218],
         [248, 286, 324, 362],
         [344, 398, 452, 506]]))

## Broadcasting

In [55]:
x = torch.rand(5, 5)
y = torch.rand(1, 5)

x - y

tensor([[ 0.0298, -0.4796, -0.5076,  0.0766, -0.3860],
        [-0.1259,  0.4081, -0.5837, -0.3810,  0.0211],
        [-0.0142, -0.0950,  0.1263, -0.2279, -0.3479],
        [ 0.4243,  0.1345, -0.3476,  0.2281, -0.1399],
        [-0.4354,  0.3311, -0.0382, -0.3135, -0.8000]])

In [56]:
y = torch.rand(5, 1)

x - y

tensor([[ 0.1720, -0.2155, -0.1104,  0.3031,  0.1960],
        [-0.5465,  0.1095, -0.7493, -0.7173,  0.0404],
        [-0.0149,  0.0263,  0.3806, -0.1442,  0.0913],
        [ 0.2387,  0.0708, -0.2782,  0.1267,  0.1143],
        [-0.9317, -0.0432, -0.2796, -0.7255, -0.8565]])

## Indexing

In [57]:
B, features = 10, 25

In [58]:
x = torch.rand(B, features)

In [59]:
x[0].shape

torch.Size([25])

In [60]:
x[:, 0].shape

torch.Size([10])

In [61]:
x[1:3, 0:10].shape

torch.Size([2, 10])

In [62]:
x[0, 0] = 100

In [63]:
x = torch.arange(10)
indices = [2, 5, 8]

x[indices]

tensor([2, 5, 8])

In [64]:
x = torch.rand((3, 5))

rows = [1, 0]
cols = [4, 0]

x[rows, cols]

tensor([0.4194, 0.9144])

In [65]:
x = torch.arange(10)

In [66]:
x[(x < 2) | (x > 8)]

tensor([0, 1, 9])

In [67]:
x[x % 2 == 0]

tensor([0, 2, 4, 6, 8])

In [68]:
torch.where(x > 5, x, x*2)

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])

In [69]:
x.unique()

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
x = torch.rand(5, 6)

In [71]:
x.ndimension()

2

In [72]:
x.numel()

30

## View vs Reshape

In [73]:
x = torch.arange(9)

In [74]:
x_3x3 = x.view(3, 3)
x_3x3

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [75]:
x_3x3 = x.reshape(3, 3)
x_3x3

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [76]:
y = x_3x3.t()
y

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

In [77]:
try:
    y.view(9)
except Exception as e:
    print("as they are not contiguous")
    print(e)

as they are not contiguous
view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.


In [78]:
y.contiguous().view(9)

tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])

In [79]:
y.reshape(9)

tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])

## Concat

In [80]:
x = torch.rand(2, 5)
y = torch.rand(2, 5)

In [81]:
torch.cat((x, y), dim=0).shape

torch.Size([4, 5])

In [82]:
torch.cat((x, y), dim=1).shape

torch.Size([2, 10])

In [83]:
x = torch.rand(4, 5, 6)

x.permute(0, 2, 1).shape

torch.Size([4, 6, 5])

In [84]:
x = torch.arange(10)

x.unsqueeze(0).shape, x.unsqueeze(1).shape

(torch.Size([1, 10]), torch.Size([10, 1]))

In [85]:
x = x.unsqueeze(0).unsqueeze(2)

x.shape

torch.Size([1, 10, 1])

In [86]:
x.squeeze().shape

torch.Size([10])

In [87]:
x.squeeze(0).shape

torch.Size([10, 1])