In [3]:
import torch
import numpy as np
from torchmetrics.retrieval import RetrievalMAP

In [4]:
K=10

In [5]:
truth = torch.rand(2, 20)
truth = torch.where(truth >= 0.5, 1, 0)
preds = torch.rand(2, 20)

print(preds)
print(truth)

tensor([[0.6656, 0.5945, 0.0892, 0.9180, 0.0796, 0.8824, 0.2905, 0.9724, 0.9883,
         0.0277, 0.3655, 0.5352, 0.9656, 0.7303, 0.2612, 0.9090, 0.8597, 0.6144,
         0.4857, 0.6125],
        [0.7213, 0.7786, 0.6036, 0.0955, 0.8429, 0.1822, 0.4042, 0.7078, 0.8250,
         0.8748, 0.3610, 0.1361, 0.1893, 0.0465, 0.1714, 0.5855, 0.0614, 0.6153,
         0.4505, 0.3124]])
tensor([[0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1]])


In [9]:
top_k_indices = torch.topk(preds, k=K)[1]
top_k_indices

tensor([[ 8,  7, 12,  3, 15,  5, 16, 13,  0, 17],
        [ 9,  4,  8,  1,  0,  7, 17,  2, 15, 18]])

In [11]:
top_k_truth_values = torch.gather(truth, 1, top_k_indices)
top_k_truth_values

tensor([[1, 0, 0, 1, 0, 1, 0, 0, 0, 0],
        [1, 0, 1, 1, 0, 1, 0, 0, 0, 1]])

In [29]:
cum, tot = 0, 0

for i in range(top_k_truth_values.size(0)):
    cum += int((top_k_truth_values[i, :] == 1).nonzero().size(0) > 0)
    tot += 1

hit = cum / tot
hit

1.0