In [5]:
import torch
import numpy as np
from torchmetrics.retrieval import RetrievalMRR

In [2]:
truth = torch.rand(2, 20)
truth = torch.where(truth >= 0.5, 1, 0)
preds = torch.rand(2, 20)

print(preds)
print(truth)

tensor([[2.3157e-01, 7.2313e-01, 9.7114e-01, 8.0252e-01, 3.3026e-02, 8.2050e-01,
         9.4361e-01, 6.0403e-01, 3.7185e-01, 1.8687e-01, 9.2505e-01, 1.7455e-01,
         6.9432e-01, 2.3404e-01, 3.8303e-01, 8.9583e-01, 1.4428e-01, 2.2662e-01,
         9.1523e-01, 3.8583e-01],
        [9.2992e-03, 4.2675e-01, 9.1105e-01, 3.8866e-01, 2.7772e-01, 1.3971e-01,
         1.1660e-01, 7.9097e-01, 2.3641e-01, 8.4567e-01, 2.9572e-01, 9.3304e-01,
         2.3901e-01, 5.4205e-01, 3.5965e-04, 8.1711e-01, 6.1284e-01, 2.3958e-01,
         7.3325e-01, 3.6667e-01]])
tensor([[0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1],
        [0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0]])


In [15]:
pred_ranking = preds.argsort(descending=True, dim=1)
pred_ranking

tensor([[ 2,  6, 10, 18, 15,  5,  3,  1, 12,  7, 19, 14,  8, 13,  0, 17,  9, 11,
         16,  4],
        [11,  2,  9, 15,  7, 18, 16, 13,  1,  3, 19, 10,  4, 17, 12,  8,  5,  6,
          0, 14]])

In [17]:
pred_ranks_truth = torch.gather(truth, 1, pred_ranking)
pred_ranks_truth

tensor([[0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0],
        [1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0]])

In [22]:
ranks = (pred_ranks_truth == 1).float().argmax(dim=1) + 1

In [23]:
rr = 1.0 / ranks
rr

tensor([0.2500, 1.0000])

In [25]:
mrr = rr.mean()
mrr

tensor(0.6250)

# Validation

In [26]:
mrr = RetrievalMRR()

indexes = torch.tensor([[i] * truth.size(1) for i in range(truth.size(0))])
mrr(preds.flatten(), truth.flatten(), indexes=indexes.flatten())

tensor(0.6250)