In [1]:
import torch
import numpy as np
from torchmetrics.retrieval import RetrievalPrecision

In [2]:
K = 10

In [3]:
truth = torch.rand(2, 20)
truth = torch.where(truth >= 0.5, 1, 0)
preds = torch.rand(2, 20)

print(truth)
print(preds)

tensor([[1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1],
        [1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0]])
tensor([[0.1178, 0.1989, 0.7494, 0.2079, 0.6569, 0.6981, 0.6610, 0.1199, 0.8614,
         0.3694, 0.5090, 0.4760, 0.8995, 0.4400, 0.9814, 0.1802, 0.2111, 0.1039,
         0.4368, 0.8193],
        [0.9768, 0.7369, 0.8575, 0.7330, 0.3215, 0.8537, 0.7263, 0.9917, 0.6288,
         0.1281, 0.8372, 0.3063, 0.1469, 0.6352, 0.9181, 0.1906, 0.1552, 0.4872,
         0.9725, 0.3317]])


In [4]:
indices = torch.topk(preds, k=K)[1]
preds, indices

(tensor([[0.1178, 0.1989, 0.7494, 0.2079, 0.6569, 0.6981, 0.6610, 0.1199, 0.8614,
          0.3694, 0.5090, 0.4760, 0.8995, 0.4400, 0.9814, 0.1802, 0.2111, 0.1039,
          0.4368, 0.8193],
         [0.9768, 0.7369, 0.8575, 0.7330, 0.3215, 0.8537, 0.7263, 0.9917, 0.6288,
          0.1281, 0.8372, 0.3063, 0.1469, 0.6352, 0.9181, 0.1906, 0.1552, 0.4872,
          0.9725, 0.3317]]),
 tensor([[14, 12,  8, 19,  2,  5,  6,  4, 10, 11],
         [ 7,  0, 18, 14,  2,  5, 10,  1,  3,  6]]))

In [5]:
selected_truth = torch.gather(truth, 1, indices)
selected_preds = torch.gather(preds, 1, indices)

selected_truth, selected_preds

(tensor([[1, 1, 1, 1, 0, 0, 1, 1, 0, 0],
         [1, 1, 0, 1, 0, 1, 1, 0, 0, 0]]),
 tensor([[0.9814, 0.8995, 0.8614, 0.8193, 0.7494, 0.6981, 0.6610, 0.6569, 0.5090,
          0.4760],
         [0.9917, 0.9768, 0.9725, 0.9181, 0.8575, 0.8537, 0.8372, 0.7369, 0.7330,
          0.7263]]))

In [6]:
pre_k = selected_truth.sum(dim=1) / K
print(pre_k)
pre_k = torch.mean(pre_k)
pre_k

tensor([0.6000, 0.5000])


tensor(0.5500)

# Validation

In [8]:
p2 = RetrievalPrecision(top_k=K)

indexes = torch.tensor([[i] * truth.size(1) for i in range(truth.size(0))])
p2(preds.flatten(), truth.flatten(), indexes=indexes.flatten())

tensor(0.5500)