In [1]:
import torch
import numpy as np
from torchmetrics.retrieval import RetrievalRecall

In [2]:
K = 10

In [3]:
truth = torch.rand(2, 20)
truth = torch.where(truth >= 0.5, 1, 0)
preds = torch.rand(2, 20)

print(preds)
print(truth)

tensor([[0.6247, 0.4400, 0.4081, 0.5128, 0.5923, 0.1204, 0.5968, 0.1180, 0.6544,
         0.9898, 0.1868, 0.0067, 0.7584, 0.4192, 0.7710, 0.6368, 0.6760, 0.0105,
         0.8750, 0.0961],
        [0.8300, 0.2517, 0.1792, 0.7540, 0.9734, 0.0334, 0.1494, 0.2747, 0.3824,
         0.7802, 0.1922, 0.2298, 0.3917, 0.7596, 0.1827, 0.1493, 0.7276, 0.2286,
         0.0395, 0.4883]])
tensor([[1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1],
        [1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1]])


In [4]:
indices = torch.topk(preds, k=K)[1]
preds, indices

(tensor([[0.6247, 0.4400, 0.4081, 0.5128, 0.5923, 0.1204, 0.5968, 0.1180, 0.6544,
          0.9898, 0.1868, 0.0067, 0.7584, 0.4192, 0.7710, 0.6368, 0.6760, 0.0105,
          0.8750, 0.0961],
         [0.8300, 0.2517, 0.1792, 0.7540, 0.9734, 0.0334, 0.1494, 0.2747, 0.3824,
          0.7802, 0.1922, 0.2298, 0.3917, 0.7596, 0.1827, 0.1493, 0.7276, 0.2286,
          0.0395, 0.4883]]),
 tensor([[ 9, 18, 14, 12, 16,  8, 15,  0,  6,  4],
         [ 4,  0,  9, 13,  3, 16, 19, 12,  8,  7]]))

In [5]:
selected_truth = torch.gather(truth, 1, indices)
selected_preds = torch.gather(preds, 1, indices)

selected_preds, selected_truth

(tensor([[0.9898, 0.8750, 0.7710, 0.7584, 0.6760, 0.6544, 0.6368, 0.6247, 0.5968,
          0.5923],
         [0.9734, 0.8300, 0.7802, 0.7596, 0.7540, 0.7276, 0.4883, 0.3917, 0.3824,
          0.2747]]),
 tensor([[1, 1, 1, 1, 0, 0, 0, 1, 0, 1],
         [1, 1, 0, 0, 0, 0, 1, 0, 0, 1]]))

In [6]:
re_k = selected_truth.sum(dim=1) / truth.sum(dim=1)
print(re_k)
re_k = torch.mean(re_k)
re_k

tensor([0.5000, 0.4000])


tensor(0.4500)

# Validation

In [7]:
p2 = RetrievalRecall(top_k=K)

indexes = torch.tensor([[i] * truth.size(1) for i in range(truth.size(0))])
p2(preds.flatten(), truth.flatten(), indexes=indexes.flatten())

tensor(0.4500)